# Generated by Django 3.2.12 on 2022-04-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


TICKERS = [
    ("Bitcoin", "BTC"),
    ("Tether", "USDT"),
    ("Ethereum", "ETH"),
    ("Litecoin", "LTC"),
]


def data_insert(apps, schema_editor):
    Ticker = apps.get_model("balance", "Ticker")

    for ticker in TICKERS:
        Ticker(name=ticker[0], code=ticker[1]).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="update date"),
                ),
                ("amount", models.FloatField(verbose_name="amount")),
            ],
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="ticker name")),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="ticker code"
                    ),
                ),
                (
                    "enable",
                    models.BooleanField(
                        choices=[(True, "Enable"), (False, "Disable")],
                        default=True,
                        verbose_name="Enable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticker",
                "verbose_name_plural": "Tickers",
                "ordering": ["-code"],
            },
        ),
        migrations.CreateModel(
            name="BalanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="amount received")),
                ("amount_before", models.FloatField(verbose_name="amount before")),
                ("amount_after", models.FloatField(verbose_name="amount after")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("airdrop", "Airdrop"),
                            ("burn", "Burn"),
                            ("peer_to_peer", "Peer to Peer"),
                        ],
                        default="airdrop",
                        max_length=12,
                    ),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="balance.balance",
                        verbose_name="balance ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="balance",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="balance.ticker",
                verbose_name="ticker ID",
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user ID",
            ),
        ),
        migrations.RunPython(data_insert),
    ]
